#! /bin/bash
# This script is designed and implemented by Jason Koo on 20150106.
# This script is dependent on dategen, monthgen script.
# Usage: ./alter-part  [configFile location]
if [ -z "$1" ]; then
    echo "Configuration file must be provided !"
    echo "Usage: $0 [configFile location]"
    exit 1
fi

DIR=$(cd $(dirname "$0"); pwd)

echo "---------------------------------------------------------------------------------------------------------------------"
echo
echo $(date +"%Y%m%d %T")
echo
configFile=$1
grep -v '^#' $configFile | while read basePath db tbl partname partscript adddiff dropdiff useJAR;
do
    echo "Start altering partitions for $db.$tbl ."
    hiveQL=""
    if [ "$useJAR" -eq 1 ]; then
        hiveQL+="ADD JAR /home/lestat/jar/lestat-hive-0.0.1-SNAPSHOT.jar; "
    fi
    hiveQL+="use $db; "
    # Prepare HiveQL for adding partition
    partvalue=$($DIR/$partscript $adddiff)
    partdir="$basePath/$db/$tbl/$partvalue"
    if hadoop fs -test -e $partdir ; then
        echo "partition $partname='$partvalue' to be added ."
        hiveQL+="ALTER TABLE $tbl ADD IF NOT EXISTS PARTITION ($partname = '$partvalue') LOCATION '$partdir'; "
    else
        echo "$partdir does not exist !"
    fi
    
    # Prepare HiveQL for dropping partition
    partvalue=$($DIR/$partscript $dropdiff)
    echo "partition $partname='$partvalue' to be dropped ."
    hiveQL+="ALTER TABLE $tbl DROP IF EXISTS PARTITION ($partname = '$partvalue'); "    
    echo "hiveQL to be executed: $hiveQL"
    hive -e "$hiveQL"
    echo "End altering partitions for $db.$tbl ."
done
